version: "3"

services:
  bot-250-ping-god:
    build: ./src/Bot250PingGod/
    environment:
      ConnectionStrings__Default: User ID=t2elzeth;Password=123;Host=database;Port=5432;Database=bot_250_ping_god_db;Pooling=true
    networks:
      - bot-250-ping-god-net
    stdin_open: true
    tty: true

  database:
    image: postgres:14
    container_name: bot-250-ping-god-db
    networks:
      - bot-250-ping-god-net
    volumes:
      - "bot-250-ping-god-db-data:/var/lib/postgresql/data"
      - ./migrations/create-database:/docker-entrypoint-initdb.d
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: 123

networks:
  bot-250-ping-god-net:
    driver: bridge
volumes:
  bot-250-ping-god-db-data:
    name: "bot-250-ping-god-db-data"
